frontend/static/css/components.css

Edit profile layout fix

---

frontend/html/posts/items/battle.html
frontend/html/posts/items/intro.html
frontend/html/posts/items/link.html
frontend/html/posts/items/pain.html
frontend/html/posts/items/post.html
frontend/html/posts/items/project.html
frontend/html/posts/items/question.html
frontend/static/css/base.css
frontend/static/css/components.css
frontend/static/css/layout.css

Fixed posts links

---

frontend/html/users/widgets/small.html
frontend/static/css/layout.css

I found some issues on my mobile in the user footer section. I suppose that there is should be bottom padding.
Before fix was [this](https://s.csssr.ru/U439TP407/20200427225208.png), on my mobile it was like [this](http://s.csssr.ru/U439TP407/photo_2020-04-27_23.08.53.jpeg)
After my fix it will be like [this](https://s.csssr.ru/U439TP407/20200427230718.png) and the real screenshot from my mobile – [link](http://s.csssr.ru/U439TP407/photo_2020-04-27_23.08.57.jpeg)
Also, I removed some unnecessary styles.

Fix user footer for mobile

---

frontend/html/users/widgets/small.html
frontend/static/css/layout.css

Revert "Fix user footer for mobile"

---

frontend/static/css/components.css

Fixed label text color in draft

---

frontend/html/posts/compose/battle.html
frontend/html/posts/compose/link.html
frontend/html/posts/compose/pain.html
frontend/html/posts/compose/post.html
frontend/html/posts/compose/project.html
frontend/html/posts/compose/question.html

Это поправит ишью #28 
Я не уверен кстати насчет редактирования боли, потому что там ничего изначально не было. Потому я вставил в заголовок "Расскажи где болит", если это не ок, то надо поправить.

Заголовки при редактировании

---

frontend/html/posts/items/battle.html

Правит ишью #27, как и сказали можно переименовать аругменты в комментарии

Аргументы -> комментарии на карточке батла

---

frontend/html/posts/feed.html
frontend/html/posts/widgets/topic.html
frontend/static/css/components.css

Было / стало, поправил по мимо выравнивания кейс с нечетным количеством рум
Мобильное отображение не трогал

Topics beautify

---

frontend/static/js/main.js

Fix theme switcher based on system scheme if user hasn't selected theme yet

---

frontend/html/posts/feed.html
frontend/html/posts/widgets/topic.html
frontend/static/css/components.css

Revert "Topics beautify"

---

comments/models.py
posts/models.py

Проблема: в локальном окружении один пользователь и апвоутить самого себя нельзя.
Элегантное (ну почти) решение: разрешить Богу апвоутить свои посты/комментарии. Как вам такое, атеисты?

Allow God to upvote his comments/posts

---

frontend/static/js/main.js

Add force resync of codemirror editors content based on attached textarea value after page loaded.
Cases when applicable (checked in Chrome on Linux/Mac):
1) you write a comment, hit 'send' and 502 occurs. If you hit back button, codemirror initiates with no content, and textarea value is restored (but async, might need to look up reasons to that)
2) you write comment, hit 'send' and then navigate back. If you do nothing and hit send you get 200 OK response with html page saying something went wrong.
I tried this with minimal markdown in comments & posts and it seem not to mess up regular autosave, but further QA might be needed.
Some other minor changes are due to prettier, quotes are okay, I guess, trailing comma might be debatable, let me know, if you don't want that. Oh, and I see …

Fix vanishing comments if deploy is in process

---

frontend/html/users/profile.html
frontend/static/css/components.css

Правит #62 
Добавил редактирования интро в профиле. Посмотрел в хроме, фф и сафари.
На мобилках будет примерно так.

Редактирование интро в профиле

---

frontend/package-lock.json
frontend/package.json
frontend/static/css/index.css
frontend/webpack.config.js

- Чистая `dist/` для watch режима;
- Минифицирует только для прода;
- Удаляет опасные `./node_modules/.bin/` из скриптов — npm надёжнее определит путь;
- Объединяет запросы за внешними шрифтами;

Доработка сборки фронта

---

frontend/package.json
frontend/postcss.config.js
frontend/webpack.config.js

Забыл что конфиги в лоадере и в `package.json` не мержатся а перезаписываться. Вынес в отдельный конфиг.

Исправляет ошибку в конфигурации postcss

---

frontend/html/common/paginator.html
posts/templatetags/query_params.py

Have query inside search URL so existing paginator has correct links

---

frontend/html/comments/forms/reply.html
frontend/static/js/main.js

Решает https://github.com/vas3k/vas3k.club/issues/70
Опционально, можно добавить под поле ввода комментария хинт о том, что можно использовать хоткей. Хотя, наверное, многие уже настолько привыкли к этой механике что будут на автомате пытаться отправлять комментарии так.

Хоткей отправки комментария

---

frontend/static/css/posts.css

added z-index for upvote on small screens
Fixes #118

Fix unreachable upvote button

---

frontend/static/css/components.css

fix inconsistent intro fonts

---

frontend/html/users/profile.html
frontend/static/css/components.css

Expertise label

---

frontend/html/posts/widgets/battle_stats.html
frontend/static/css/posts.css
frontend/static/css/theme.css
posts/templatetags/battle.py

Fixes #129 
Очень сложно этот ваш фронтэнд :-(

somehow added graph for battle results

---

.github/workflows/CI.yml

Что сделал:
При каждом pull_request теперь код проверяется линтером `make test-ci`, если проверка удачная, то происходит попытка поднять весь docker-compose, зайти внутрь контейнера `club_app` и запустить миграции `make migrate`
Если оба действия имеют код возврата 0, то CI считается успешно завершенным

Add actions-ci

---

frontend/package-lock.json
frontend/package.json
frontend/static/css/base.css
frontend/static/css/theme.css
frontend/static/js/App.js
frontend/static/js/codemirror-4.inline-attachment.js
frontend/static/js/common/api.service.js
frontend/static/js/common/domUtils.js
frontend/static/js/components/CommentUpvote.vue
frontend/static/js/components/PostUpvote.vue
frontend/static/js/components/UserExpertiseWindow.vue
frontend/static/js/components/UserTag.vue
frontend/static/js/inline-attachment.js
frontend/static/js/main.js

Дратути, я начал делать блокировку кнопки при комментировании, но наткнулся на то, что отправка по <kbd>Cmd</kbd>+<kbd>Enter</kbd> и по <kbd>Ctrl</kbd>+<kbd>Enter</kbd> не работало, поэтому решил это подфиксить. 
По сути можно глянуть только первый коммит, во втором только форматирование.
+ я добавил prettier, чтобы форматирование было у всех одинаковое.

Submit on Cmd|Ctrl+Enter. Prettier

---

frontend/package-lock.json
frontend/package.json
frontend/static/css/base.css
frontend/static/css/theme.css
frontend/static/js/App.js
frontend/static/js/codemirror-4.inline-attachment.js
frontend/static/js/common/api.service.js
frontend/static/js/common/domUtils.js
frontend/static/js/components/CommentUpvote.vue
frontend/static/js/components/PostUpvote.vue
frontend/static/js/components/UserExpertiseWindow.vue
frontend/static/js/components/UserTag.vue
frontend/static/js/inline-attachment.js
frontend/static/js/main.js

Revert "Submit on Cmd|Ctrl+Enter. Prettier"

---

frontend/static/css/posts.css

Fixed #196 - pre with horizontal scroll

---

notifications/signals/comments.py

Сейчас подписчику на комменты приходит авторский текст (💬 Новый коммент к **вашему** посту ...), поправил так, чтобы приходил простой, без "вашему".

Send different comment notifications to post author and post subscriber

---

common/regexp.py

Allow tagging usernames with dashes

---

frontend/static/js/App.js

will fix https://github.com/vas3k/vas3k.club/issues/226
Я думаю, что этот метод устарел и там какие-то проблемы байдинга(это же жээс), я попробовал аплаить контекст напрямую, но че-то не помогло, проще просто по-тупому поставить листенеры на форму

directly pass listeners to form by editor

---

frontend/html/comments/types/normal.html

Fix comments dates display

---

.prettierrc
frontend/html/users/edit/profile.html
frontend/static/js/components/UserAvatarInput.vue
frontend/static/js/main.js

#247 
Добавил компонент с первью выбранной аватарки для страницы "Редактирование профайла". 
При клике на кружок открывается окошко выбора файла. 
Изначально показывается текущий аватар пользователя.

Редактирование профиля | Добавил превью аватарки  

---

frontend/html/common/menu-full.html
frontend/html/posts/feed.html
frontend/static/css/components.css
frontend/static/css/layout.css
frontend/static/js/components/SidebarToggler.vue
frontend/static/js/main.js

Накидал по-быстрому вот такую менюху:
https://monosnap.com/file/BiNnRvTCW507oB9NiNCrDR6yhm4vnW
Есть идеи, как улучшить?
will fix #178 
will fix #197

Implement mobile menu

---

README.md
auth/views/auth.py
club/urls.py

Will close #255
Создается по ссылке http://127.0.0.1:8000/godmode/random_login/

Создание тестового юзера

---

users/views.py

fix for issue #262

---

common/data/achievements.py

Вроде только тут надо поменять

color issues fix

---

Makefile
frontend/static/css/components.css
frontend/static/css/components/people.css
frontend/static/js/components/PeopleMap.vue
users/templatetags/users.py

Ничего красивого что-то не придумал - просто текст на попапе

Добавил попап по наведению - имя, должность и компания

---

Makefile
frontend/static/css/components/people.css
frontend/static/js/components/PeopleMap.vue
users/templatetags/users.py

Revert "Добавил попап по наведению - имя, должность и компания"

---

frontend/static/js/App.js

[feature] move the cursor to the left/right side of the visual line it is on (Home/End)

---

frontend/static/css/components.css
frontend/static/js/components/SidebarToggler.vue

Плохо кнопку видно.
Было:
Стало:

[#302] Добавил рамку в кнопке открытия меню на мобильной версии

---

frontend/html/auth/access_denied.html
frontend/html/misc/achievements.html
frontend/html/misc/network.html
frontend/html/posts/feed.html
frontend/html/posts/show/layout.html
frontend/html/search.html
frontend/html/users/people.html
frontend/html/users/profile.html

https://github.com/vas3k/vas3k.club/pull/320 – this wasn't enough, there are way more wrong Twitter tags:
- changed `summary_image` to `summary`
Now it should be finally over.

Fix all Twitter tags

---

Makefile
dev.dockerfile
dev_requirements.txt

Closes #324 
— Добавил скрипт в Makefile для генерации файла dev-зависимостей.
— Добавил установку dev-зависимостей при запуске в докере.

Bug 324 Dev-зависимости в докере

---

club/settings.py
frontend/static/css/components.css
frontend/static/css/theme.css

Closes #318 
Поправил цвета в тёмной теме. Проверил на десктопе и на мобилке, светлая тема не сломалась.

Bug 318 Фикс цветов в тёмной теме

---

frontend/html/comments/types/battle.html
frontend/html/comments/types/bold.html
frontend/html/comments/types/normal.html
frontend/html/comments/types/reply.html
frontend/html/posts/items/battle.html
frontend/html/posts/items/idea.html
frontend/html/posts/items/intro.html
frontend/html/posts/items/link.html
frontend/html/posts/items/pain.html
frontend/html/posts/items/post.html
frontend/html/posts/items/project.html
frontend/html/posts/items/question.html
frontend/html/posts/show/battle.html
frontend/html/posts/show/idea.html
frontend/html/posts/show/link.html
frontend/html/posts/show/pain.html
frontend/html/posts/show/post.html
frontend/html/posts/show/project.html
frontend/html/posts/show/question.html
frontend/html/search.html

Переводит кнопки +1 в readonly режим на страницах поиска.
Частично решает (Closes #311), но все равно не видно, какие посты ты уже апвоутил.

Disable upvote action on the search results page

---

posts/forms/compose.py

issue #337 fix 500 for wrong link value

---

notifications/templates/telegram/comment_to_post.html

Closes #317 
Протестировано на локалке, отрабатывает как и ожидается.

fix 317: Don't show None battleside in reply to argument

---

frontend/html/posts/compose/battle.html
frontend/html/posts/compose/link.html

Спасибо @dimabory за наводку! 
Выкидываем бесполезный код

Remove rubbish code

---

frontend/html/users/intro.html
frontend/static/js/components/InputLengthCounter.vue
frontend/static/js/main.js

Adding intro text counter

---

frontend/html/auth/email.html

just made it numeric. see the difference (please ignore green background, this is web inspector):

OTP-friendly keyboard type

---

frontend/static/js/components/InputLengthCounter.vue

closes #375 
https://vuejs.org/v2/guide/conditional.html#Controlling-Reusable-Elements-with-key

Fix emoji switcher within #intro counter

---

common/data/expertise.py
users/forms/profile.py
users/models/expertise.py

Fixed bug with same custom expertise name

---

posts/templatetags/query_params.py

Fixed bug with pagination on community page

---

frontend/html/posts/compose/link.html
frontend/html/posts/compose/project.html
frontend/static/js/App.js
posts/forms/compose.py

Use #intro counter in posts (project & link)

---

README.md
docker-compose.yml

В ходе работы над https://github.com/vas3k/vas3k.club/pull/371 и написанием readme к нему осознал, что для запуска тестов необходимо много всего настроенного локально — venv, postgress, сбилженный фронт и т.д. Хоть в ci это запускается все автоматически, но для локальной разработки требуются ручные манипуляции.
В общем, добавил в доку описание для настройки локального окружения.
Не являюсь носителем языка, поэтому предложения и исправления — welcome
Возможно какие-то шаги избыточны, поэтому если заметил — пиши
Known issues:

[documentation] Local development

---

notifications/telegram/templates/messages/comment_to_post_announce.html

Исправляет "за «None»" в уведомлениях о реплаях к постам-батлам.

Fix battle reply notification

---

club/urls.py
misc/views.py

Add a simple static `robots.txt` to this very amazing project!

Fix #387: Simple robots.txt

---

frontend/static/css/components.css

will fix vas3k/vas3k.club#402
Немного уменьшил шрифт и отступы

Fix #402: Upvote button issue on mobile

---

frontend/static/css/base.css

* Fix #394 icons alignments on android

issue #394: fix icons alignment on android

---

frontend/html/emails/daily.html
frontend/html/emails/weekly.html

issue #397: fix weekly digest intros html escaping

---

frontend/html/users/edit/profile.html
frontend/html/users/intro.html

Fix #408: remove text about contact field optionality

---

frontend/html/users/edit/notifications.html
frontend/static/css/components.css
frontend/static/css/theme.css

issue#416: Fixed styles in notifications page

---

frontend/html/layout.html

Я своим предыдущим ПР-ом #425 поломал немного подгрузку темы. Сорри @vas3k 
Если тема стоит белая, то всё норм, но если тёмная - то тогда происходят лаги с перерисовкой.

Get back theme switcher script to <head/>

---

frontend/html/comments/types/snippet.html

Use small version of upvotes for snippet in search and profile

---

frontend/static/css/layout.css

Set up <select> width to fit the page in mobile devices

---

.github/workflows/telegram.yml
frontend/html/comments/types/snippet.html

- Необходимо заменить айдишник тестовый на айдишник чата
- Необходимо засетить token в settings
Прежде чем вливать необходимо прописать в secrets токен бота `token`

Добавление поддержки Telegram бота из коробки

---

.github/actions/tg/send_message.sh

Now we report message with link preview
Report message without link preview

Disable web page preview for telegram message

---

bookmarks/views.py

unread_comments считаются как доп-поля к посту только в методе `objects_for_user`.

Fixing issue #496

---

frontend/html/comments/edit.html
frontend/html/comments/forms/battle.html
frontend/html/comments/forms/comment.html
frontend/html/comments/forms/reply.html
frontend/html/comments/types/bold.html
frontend/html/comments/types/normal.html
frontend/html/comments/types/reply.html
frontend/html/comments/types/snippet.html
frontend/html/common/menu-full.html
frontend/html/feed.html
frontend/html/landing.html
frontend/html/posts/items/battle.html
frontend/html/posts/items/event.html
frontend/html/posts/items/idea.html
frontend/html/posts/items/intro.html
frontend/html/posts/items/link.html
frontend/html/posts/items/pain.html
frontend/html/posts/items/post.html
frontend/html/posts/items/question.html
frontend/html/posts/widgets/topic.html
frontend/html/users/widgets/card.html
frontend/html/users/widgets/hat.html
frontend/html/users/widgets/small.html
frontend/html/users/widgets/tiny.html
frontend/static/css/base.css
frontend/static/css/components.css

Собственно, как заказывали #506. В хроме и лисе работает норм, в сафари не тестил, к сожалению (нет возможности).
Некоторые места (вроде рассылок и интро) не трогал. Но потом можно будет и там переделать по аналогии, наверно.

Переделал картинки с background-image на <img />

---

docs/setup.md

requirements.dev.txt -> dev_requirements.txt

Fix dev requirements filename in setup.md

---

frontend/html/feed.html
frontend/html/users/edit/bot.html
frontend/html/users/edit/notifications.html
frontend/html/users/intro.html

https://github.com/vas3k/vas3k.club/issues/509

Add `rel="noreferrer"` attribute

---

frontend/html/users/profile.html
users/views/profile.py

Это пока простейший драфт, который выглядит так:
Нужен фидбек, что делать дальше (если делать).

Initial implementation for issue #341

---

posts/forms/compose.py

Small typo fix, #good first issue

Changed three dots to ellipsis in new post placeholder

---

frontend/static/js/App.js
frontend/static/js/components/CommentUpvote.vue
frontend/static/js/components/InputLengthCounter.vue
frontend/static/js/components/PeopleMap.vue
frontend/static/js/components/PostBookmark.vue
frontend/static/js/components/PostRSVP.vue
frontend/static/js/components/PostSubscription.vue
frontend/static/js/components/PostUpvote.vue
frontend/static/js/components/SidebarToggler.vue
frontend/static/js/components/StripeCheckoutButton.vue
frontend/static/js/components/UserAvatarInput.vue
frontend/static/js/components/UserTag.vue
frontend/static/js/main.js

`prettier --write ./static/js`
Не уверен надо ли это или нет, но так как `prettier` является зависимостью и даже форматирует код на pre-commit хук, возможно стоит весь уже существующий код привести к одному стилю.
https://github.com/vas3k/vas3k.club/blob/350c404a7d182b90ad80c37760e86f1c975b0450/frontend/package.json#L42-L51

Format JS code according to prettier configuration

---

posts/tests/test_views.py
posts/views/posts.py

Closes #545

---

bot/handlers/common.py

Add intro emoji to bot reaction

---

notifications/signals/comments.py
notifications/signals/posts.py
notifications/telegram/templates/messages/friend_comment.html
notifications/telegram/templates/messages/friend_post.html

It would be great if bot notifications could reflect it

Wednesday is for dudes

---

.github/actions/tg/Dockerfile
.github/actions/tg/README.md
.github/actions/tg/action.yml
.github/actions/tg/send_message.py
.github/workflows/telegram.yml

Сейчас мы фейлимся на пуллреквестах из-за того что секретный токен не прокидывается в workflow пулреквестов из форков
Теперь токен храниться прямо в CI в открытом виде. Закодирован в base64 чтобы его не находили автоматические парсеры

Inject TG token inside action

---

bot/handlers/comments.py

Я тут сделал набросок, но вообще меня в целом смущает большая разница в коде создания комментария в боте и создания комментария в вебе. Как-то бы вроде генерализовать и куда-то поместить это, но я не очень джанго эксперт, чтобы понять где и как это лучше сделать.
Ну и ещё как водится это изменение нетривиально потестить без тестового бота.

Fixing issue #648

---

frontend/html/users/intro.html

Ссылка на страницу Лены открывается не в новой вкладке, а в текущей

---

common/url_metadata_parser.py
frontend/html/posts/embeds/summary.html
posts/templatetags/posts.py

Revert "Fixing issue #667"

---

notifications/signals/posts.py
notifications/telegram/templates/messages/coauthor_added.html
notifications/telegram/templates/messages/coauthor_removed.html

Tested locally with debug prints.

Adding telegram notifications about coauthors

---

frontend/html/pages/stats.html
misc/views.py

Sorting achievements by user count and showing how many users are hidden

---

frontend/html/comments/types/battle.html
frontend/html/comments/types/bold.html
frontend/html/comments/types/normal.html
frontend/html/comments/types/reply.html

**Как было для восстановления комментария**
**Как стало**

Поменял иконку и текст при восстановлении коментарии #677

---

common/markdown/club_renderer.py
common/regexp.py

Fix for youtube playlists

---

gdpr/archive.py
gdpr/serializers.py
users/views/settings.py

[feature] Добавил лайки постов в архив данными

---

common/embeds.py
common/markdown/club_renderer.py
common/markdown/email_renderer.py
common/regexp.py
posts/templatetags/text_filters.py

Add possibility to embed links like `https://www.youtube.com/playlist?list=PLXOrZPAO2Ui021R3sKD5z0n9Qzeix9Kbj`

Add possibility to embed playlists

---

frontend/html/common/menu-simplified.html
frontend/static/css/layout.css

https://github.com/vas3k/vas3k.club/issues/714
Выглядеть должно вот так:

Issue #714

---

frontend/static/css/base.css
frontend/static/css/components/comments.css
frontend/static/css/components/compose.css
frontend/static/css/theme.css

Добавил темную темизацию для инпутов и элементов wysiwig редактора.

Add theming for dark inputs and wysiwg

---

frontend/html/users/profile.html

[Description](https://github.com/vas3k/vas3k.club/issues/744)

Fix for issue:744

---

frontend/html/posts/items/battle.html
frontend/html/posts/items/event.html
frontend/html/posts/items/idea.html
frontend/html/posts/items/intro.html
frontend/html/posts/items/link.html
frontend/html/posts/items/post.html
frontend/html/posts/items/project.html
frontend/html/posts/items/question.html
frontend/html/posts/show/battle.html
frontend/html/posts/show/event.html
frontend/html/posts/show/idea.html
frontend/html/posts/show/intro.html
frontend/html/posts/show/link.html
frontend/html/posts/show/post.html
frontend/html/posts/show/question.html
frontend/static/css/base.css
frontend/static/css/components.css
frontend/static/css/components/posts.css

Добавил нормальные переходы по табу на главной странице и подсветку выделенного блока.
Удалил лишнюю дублирующую ссылку.
На страницах постов добавил h1 заголовки.
[Ссылка на iisue](https://github.com/vas3k/vas3k.club/issues/409).
https://user-images.githubusercontent.com/17778661/140196797-5c0b913f-1539-4e0e-ad15-e26c272a9adf.mov

Improve accessibility, add heading tags

---

frontend/html/posts/items/intro.html
frontend/static/css/components.css
frontend/static/css/components/posts.css
frontend/static/css/theme.css

Исправил поехавшую верстку с intro, добавил анимацию на смену темы.

Fix intro template bug, add toggle-theme animation

---

frontend/static/css/components/posts.css

Исправление [ошибки ](https://github.com/vas3k/vas3k.club/issues/793) с длинными картинками.

Fix post image styles

---

frontend/static/css/components/comments.css

Add dark theme to autocomplete

---

frontend/static/css/components/comments.css
frontend/static/css/layout.css

Add right padding to new comments

---

common/data/achievements.py

Ошибся с цветом вчера: забыл, что фонт ачивок светлый.
Тестим на проде, соре:(

Fix diy achievement color

---

frontend/html/feed.html

From https://stackoverflow.com/questions/6257463/how-to-get-the-url-without-any-parameters-in-javascript.
Fixes: #893.

Build URL in feed-ordering-item onchange manually

---

frontend/html/comments/types/battle.html
frontend/static/css/components/comments.css

В соответствии с [пожеланием](https://github.com/vas3k/vas3k.club/discussions/882) добавил даты.
Вообще конечно нужно хорошенько подумать над ui/ux и все переверстать)

Add date links in battles

---

frontend/static/css/base.css

Из-за этих пары пикселей – начал дёргаться глаз.

fix(topic-name): unnecessary margin

---

frontend/html/posts/compose/battle.html
frontend/html/posts/compose/event.html
frontend/html/posts/compose/guide.html
frontend/html/posts/compose/idea.html
frontend/html/posts/compose/intro.html
frontend/html/posts/compose/link.html
frontend/html/posts/compose/post.html
frontend/html/posts/compose/question.html
frontend/html/posts/compose/thread.html

- Text fields show form.text.errors
- Comment templates in threads show form.comment_template.errors
Signed-off-by: Vitalii Dmitriev <dmitvitalii@gmail.com>

Show proper errors for their form elements

---

frontend/html/posts/compose/elements/post_settings.html
posts/forms/compose.py

Создание события:
Показ события:

Adding coauthors to events

---

posts/models/post.py
users/models/user.py

Add author_id in addition to author slug  helping to achieve two goals: 
- clearly identify author in case of slug change 
- make user and post endpoints more similar between each other

feat(): Add user id to api endpoints

---

frontend/html/comments/types/battle.html
frontend/html/comments/types/bold.html
frontend/html/comments/types/normal.html
frontend/html/comments/types/reply.html
frontend/html/posts/items/battle.html
frontend/html/posts/items/event.html
frontend/html/posts/items/idea.html
frontend/html/posts/items/intro.html
frontend/html/posts/items/link.html
frontend/html/posts/items/post.html
frontend/html/posts/items/project.html
frontend/html/posts/items/question.html
frontend/html/posts/show/battle.html
frontend/html/posts/show/intro.html
frontend/html/posts/show/post.html
frontend/html/posts/show/question.html
gdpr/forget.py
posts/forms/compose.py
posts/models/post.py
posts/models/votes.py
posts/templatetags/posts.py
posts/views/posts.py

Фича для учета плюсов для соавторов поста:
1) при плюсовании поста, плюс добавляется как автору, так и соавтору
2) при убирания плюса с поста, плюс убирается у автора и у соавторов (так же добавил проверку, чтобы общее количество плюсиков не могло стать меньше нуля)
3) соавторы не могут плюсовать пост (backend)
4) соавторы имеет функция плюсования disabled в ленте и в самом посте (frontend)
5) добавил невозможность добавлять одно и того же юзера в соавторы несколько раз
6) при `gdpr` `delete_user_data` убирает соавторство со всех постов
Протестировано локально 🫠

Upvote and retract vote works for coauthors

---

frontend/html/comments/types/reply.html

Hide reply button for deeper comments. See #1022

---

posts/forms/compose.py

Signed-off-by: Vitalii Dmitriev <dmitvitalii@gmail.com>

Allow to use @ symbol for coauthors

---

frontend/html/posts/show/battle.html

Fix missing scroll to arrow in battles

---

common/markdown/club_renderer.py
common/markdown/email_renderer.py

fix(): remove autoplay and loop from videos

---

posts/models/post.py
posts/tests/test_api.py

Пофиксил ишшью, добавил тесты. Проверил валидатор через локальный сервер — вроде все ок. 
Closes #1110

fix: add rfc3339 support to feed.json (and content_text visibility fix)

---

posts/forms/compose.py

Signed-off-by: Vitalii Dmitriev <dmitvitalii@gmail.com>

Fix potential iterating through None

---

frontend/static/css/components/feed.css

Date box fix

---

bot/handlers/whois.py

fix(): posts from channels detected as bots

---

frontend/html/posts/compose/elements/post_settings.html
frontend/static/js/components/TagSelect.vue

Fix https://github.com/vas3k/vas3k.club/pull/1155#pullrequestreview-1714083667

bugfix: TagSelect show only collectible tags (fix search api url)

---

comments/templatetags/comments.py
comments/views.py
frontend/html/comments/edit.html
frontend/html/comments/forms/battle.html
frontend/html/comments/forms/comment.html
frontend/html/posts/show/battle.html
frontend/html/posts/show/layout.html

Resolve #1131 edit comment battles

---

frontend/html/auth/login.html

Переход на `type=email` в форме эл. почты логина даст:
1. Жизнь по понятиям. Это почта, и у нас будет соответствующих `type`.
2. Жизнь по скорости. Во всех браузерах включается особое автозавершение, можно одним кликом ввести свою почту.
3. Жизнь по удобству. На мобилке включается особая клавиатура, где удобнее вводить почту.

Use proper type=email in loginx field for autcompletion and better UX

---

frontend/html/emails/registration.html

В вызове шаблона
`        html=registration_template.render({"user": user}),`

Fix registration template

---

frontend/html/emails/layout.html

Фикс пропердоленных аватарок

---

frontend/static/js/common/markdown-editor.js

В какой-то момент потерялись импорты функций

Фиксит отправку комментария по хотекю cmd+enter

---

frontend/html/comments/types/battle.html
frontend/html/comments/types/bold.html
frontend/html/comments/types/normal.html
frontend/html/comments/types/reply.html
frontend/static/js/components/ReplyContainer.vue
frontend/static/js/main.js

Договорились, что эта функциональность не нужна

Удаляет неработающий код ответа с цитатой 

---

frontend/static/js/components/ReplyContainer.vue

Временный фикс, пока не починим нормально

Фиксит прокрутку к якорному элементу

---

frontend/static/js/components/ReplyForm.vue

Удаляет хотфикс прокрутки

---

frontend/html/comments/forms/battle.html
frontend/html/comments/forms/comment.html
frontend/static/js/components/MarkdownEditor/DesktopMarkdownEditor.vue
frontend/static/js/components/MarkdownEditor/MarkdownEditor.vue
frontend/static/js/components/MarkdownEditor/MobileMarkdownEditor.vue
frontend/static/js/components/ReplyForm.vue
frontend/static/js/main.js

Что пофикшено с #1229:
- можно редактировать комментарии 
- исправлен баг с ответом на комментарий в батле (показывал @ вместо пустого поля)
Видосик: https://www.loom.com/share/8c0591fa5cf142d0af86eb21bbcbacec?sid=31bed954-0bf3-4a2a-ab96-9e085b79cf5f

Попытка #2. Разделяет код мобильного и десктопного редактора

---

frontend/html/comments/forms/battle.html
frontend/html/comments/forms/comment.html

Closes #1235 
Ставит фокус только в случаях, когда у сервера есть объект комментария, т.е. на экране редактирования

Убирает автофокус форму коментария

---

posts/rss.py

Добавляет дату публикации для каждого поста в RSS ленте
`docker compose up`
До: 
После:

feat: add rss item pubdate

---

frontend/static/css/layout.css

Closes #1242 
Плашка красится в темный или светлый в зависимости от выбранной темы:

Исправляет плашку загрузки картинки для темной темы

---

.github/workflows/check_build_and_run.yml
users/api.py

Fixes `/user/by_telegram_id/{id}.json` endpoint with users of the same telegram_id.

Order users by moderation status in by_telegram_id

---

frontend/static/css/components/feed.css

Revert "Padding for comment link"

---

frontend/static/css/components/feed.css

Дубль два, первый PR завернули, т.к. в лисе вёрстка немного поехала. Теперь всё ок. 
https://vas3k.club/post/26312/#comment-84d69963-7eb1-4fec-93f5-9b66aeb55ac9
На скрине зелёный и красный полуфон -- теперешняя area для кликов/тачей. Теперь промазать будет сложно. 
В ЛИСЕ ПРОВЕРИЛ!!!

Падинги для тача по комментам

---

posts/rss.py
posts/views/feed.py

This change adds an author name (slug) to RSS feeds
That is useful to configure sorting/filtering rules
```diff
<?xml version="1.0" encoding="utf-8"?>
<rss version="2.0"
xmlns:atom="http://www.w3.org/2005/Atom">
<channel>
<title>Вастрик.Клуб: Новые посты</title>
<link>http://127.0.0.1:8000/posts.rss</link>
<description></description>
<atom:link href="http://127.0.0.1:8000/posts.rss" rel="self"></atom:link>
<language>ru</language>
<lastBuildDate>Sun, 05 Jan 2025 13:58:10 +0000</lastBuildDate>
<item>
<title>Тред: ⁉️ FAQ по Вастрик Клубу. Ответы на вопросы новичков</title>
<link>http://127.0.0.1:8000/thread/faq/</link>
<description>Этот тред — официальный FAQ по Вастрик Клубу. Вы задаете вопросы — мы отвечаем. Популярные вопросы мы будем закреплять сверху, тем самым собирая здесь полноценный …
```

Add author to RSS feed

---

frontend/html/users/profile.html
frontend/html/users/widgets/card.html
users/models/user.py
users/views/profile.py

show to other users, not only moderators
explicitly state that user has not been approved yet

show profiles for non-approved users

---

frontend/html/users/profile.html

Fix Jinja template syntax error, improve conditions for profile status

fix: hotfix for PR #1285

---

frontend/html/layout.html

The initializer sets "auto" as theme value, but the value must be either "light" or "dark"

set real theme on the DOM

---

frontend/package-lock.json
frontend/package.json
frontend/static/js/components/MarkdownEditor/DesktopMarkdownEditor.vue
frontend/static/js/main.js

Пока не обрабатывал ситуацию, что автокомплит может вылезти за пределы экрана.

Рендерит автокомплит поверх редактора
