frontend/html/users/widgets/card.html, frontend/static/css/components.css
Шрифт сделал 88%, потому что при 90%, если у чела никнейм 32 символа, один символ будет переноситься на новую строку  😤
#30
=> Fix word break in profile user name

.editorconfig
I didn't set `max_line_length` because not sure how well editorconfig plugin works for different languages (I know other formatters might respect that config property as well, but still).
=> Add neutral editorconfig

frontend/html/posts/widgets/battle_stats.html, posts/templatetags/battle.py
**Общее количество голосов** это сумма голосов за **прямые** комментарии в баттле. 
Голоса за комментарии n-го уровня (например, ответ на прямой комментарий) не учитываются.
Еще можно отобразить так:
Мне лично первый вариант показался несколько чище и понятнее, но сильных предпочтений нет.
=> Add total votes for battles

frontend/static/css/components.css
otherwise if you didn't choose theme yet and have 'prefer dark=true' set on OS level you see black :crossed_swords: instead of white one
=> By default invert logo for dark themers

docker-compose.yml, frontend/package.json
Issue is - if you don't have node_modules present in `frontend/` folder, `docker-compose up` will fail (webpack - command not found).
This add running `npm install` whenever `npm run watch` is running. It's slowly only on first run, consequent are almost noop.
Also add depends_on for club, so the startup sequence is slightly different and you have a higher chance of not seeing issues caused by build files not available resulting in django error view (it's still possible)
=> Add npm install before watch

frontend/html/common/meta.html
Added apple-mobile-web-app-capable to be able to use apple-mobile-web-app-status-bar-style, so that in PWA-mode on iOS the app would have transparent status bar
=> added meta tags for transparent status bar

frontend/html/landing.html
Сейчас для неавторизованного пользователя выглядит так: ![vas3k club_](https://user-images.githubusercontent.com/24303010/81108211-03488b00-8f21-11ea-907d-34425d9a594a.png)
Стоит вынести копипасту между лендингом и основный лейаутом в общий шаблон, чтобы больше так не ошибаться.
=> Fix the loading CSS in landing

frontend/html/posts/show/layout.html
Сейчас если меняешь сортировку комментариев в посте, то страница перезагружается полностью и ты оказываешься вверху страницы.
С длинными обсуждаемыми постами выходит несколько неудобно. Заходишь, чтобы почитать новые комментарии, долго скроллишь до формы сортировки, меняешь сортировку  на "по свежести"  и скроллишь снова.
=> Include anchor in action of comments order form

frontend/static/css/posts.css
Will fix #188 
Тикет в трелло: https://trello.com/c/As0ssw23/111-мобильная-версия-клуба-элемент-счетчика-плюсов-в-intro-перекрывает-текст
В изменениях убраны `overflow: hidden` и `text-overflow: ellipsis` для тегов в посте, возможно, был не прав и оно где-то нужно.
Было:
Стало:
=> #188 Fix upvote button text overlap on mobile

frontend/static/css/components.css
Will fix #212 
Стало не идеально, но лучше. Для более качественного результата нужно менять разметку, а это затруднительно будет тестировать без #213
Было:
Стало:
=> #212 Add nowrap to comments counters

common/markdown/club_renderer.py
Браузеры имеют встроенный инструмент, который позволяет лениво загружать изображения и iframe, что позволяет быстрее загружать страницу и экономить трафик.
К примеру, этот пост https://vas3k.club/question/2166/ без lazy loading весит 26 мб, которые грузятся сразу, а если добавить атрибуты для img и iframe, то сразу загрузится только 5 мб.
Поддержка в браузерах:
=> Lazy loading for images and iframes

Dockerfile
Судя по всему, сейчас контейнер не содержит nltk либо не импортирует сам punkt, отчего роут с ссылкой валится локально.
```
club_app            |   Resource punkt not found.
club_app            |   Please use the NLTK Downloader to obtain the resource:
```
=> add nltk to dockerfile 

frontend/html/posts/items/intro.html, frontend/html/posts/show/post.html, frontend/static/css/components.css
Отображение полного имени и должности для новых интро вместо никнейма, так как хочется видеть больше данных о новых членах клуба, листая ленту. Думаю, компанию в ленте отображать не обязательно, это менее важная и постоянная информация.
Closes #229
=> Use full name and position in intro items

frontend/static/css/layout.css
Fixes #37 
Предлагаю сделать так, всё равно запиненные блоки отличаются от обычных комментариев.
Будут уже, чем обычные, зато ничего не наезжает!
Получается вот так: 
Если можно сделать как-то получше, чтобы текст обтекал именно в одном месте иконку пина — подскажи, плиз.
=> changed grid-column-end for bold comments

notifications/views.py
Сейчас меншоны фильтруются по вхождению ника:
```
.filter(text__contains=f"@{user.slug}", is_deleted=False)
```
Это приводит к тому, что у счастливчиков с никами `Max` и `MaxSuper` будет вдвое больше меншонов, чем нужно.
Чиним это заменой `text__contains` на `text__regex`:
```
.filter(text__regex=fr"@\y{user.slug}\y", is_deleted=False)
```
Результат до:
Результат после:
Closes #240.
=> [#240]: correct mentions retrieval in digest

frontend/static/css/layout.css
там `footer-right` был прибит 100 пикселями, которых иногда даже нет. теперь оно адаптивно
Было: 
Стало:
Для детальной информации: https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Grid_Layout/Relationship_of_Grid_Layout
=> Поправил лейаут в футере на мобилках

frontend/html/comments/types/battle.html
Заметил неприятный момент в батле — декапитализация аргумента в углу коммента часто работает очень плохо.
Попытался придумать ультимейт способ, но не смог, поэтому подумал что лучше привести все строки такого рода к общему виду, так же как это сделано в самом верху страницы.
=> Remove decapitalizing from battle comments

comments/views.py, posts/models.py
Пришел написать что-нибудь во фронтенде, но в итоге пофиксил счетчик непрочитанных сообщений.
Добавил статический метод, который делает декремент счетчика непрочитанных сообщений.
Оба метода — декремент и инкремент обновляют счетчик непрочитанных только для тех пользователей, которые приходили до даты создания комментария. Если удалили или восстановили старый комментарий, он не появится в счетчике.
Closes #252
=> Считаем новые сообщения правильно

Makefile
Just load tags in docker-run-dev command
Fix #272
```
python ./utils/wait_for_postgres.py
Waiting for postgres
Waiting for postgres
Waiting for postgres
Postgres had started
python manage.py migrate
Operations to perform:
Apply all migrations: auth, comments, django_q, landing, posts, search, users
Running migrations:
Applying users.0001_initial... OK
Applying auth.0001_initial... OK
Applying posts.0001_initial... OK
Applying comments.0001_initial... OK
Applying comments.0002_auto_20200416_0937... OK
...
Applying users.0011_auto_20200526_1126... OK
Applying users.0012_auto_20200602_1121... OK
Applying users.0013_auto_20200602_1139... OK
python manage.py update_tags
42 hobbies
48 personal
0 tech
23 club
Done 🥙
python manage.py runserver 0.0.0.0:8000
Watching for file changes with …
```
=> Load tags in docker-run-dev

notifications/management/commands/send_weekly_digest.py, notifications/templates/emails/layout.html, notifications/views.py
Closes #170 
Объяснял в самом баге варианты исправления, которые я вижу:
* парсить отрендеренный html и выкидывать footer перед сохранением поста. Не нравится, потому что слишком неочевидно
* добавить к запросу на рендеринг дайджеста параметр запроса no_footer, который будет рендерить страницу без футера со ссылками. Это более читаемо, но тогда при рассылке придется два раза кинуть запрос на рендер дайджеста — с футером и без него
Я выбрал второй вариант, но готов все поменять, если это не подходит
=> Скрыть ссылки «отписаться от дайджеста» из футера

frontend/static/js/App.js
Closes #298 
Значение, использованное для `z-index` либы, которая показывает картинки было слишком большое. `z-index` бэкграунда считается как `z-index картинки - 1`. Это приводило к переполнению целочисленного диапазона значений и в итоге к бэкграунду применялось `z-index: -1;`
Решение: уменьшить z-index
До | После
------------ | -------------
=> Fix: части сайта просвечивают через бэкграунд при просмотре полноразмерных картинок

frontend/static/css/theme.css
closes #296 
Не смог понять, зачем @vas3k сделал `optimizeLegibility`, но с `optimizeSpeed` на iOS 14/macOS Big Sur шрифты становятся нормальными. В других ОС/браузерах шрифт остался таким же, но незначительно поменялось расстояние между некоторыми буквами
=> [fix] #296 fix text-rendering for iOS 14/macOS Big Sur

frontend/static/css/base.css
Before:
After:
Если это не авторская задумка, то должно пофиксить.
=> Fixed tags size and tags mobile view.

frontend/html/common/og.html
If you check any public URL(e.g. https://vas3k.club/project/4060/) with [Twitter Card Validator](https://cards-dev.twitter.com/validator), you'll get:
```
INFO:  Page fetched successfully
INFO:  19 metatags were found
INFO:  twitter:card = summary_image tag found
ERROR: The 'summary_image' card type provided by the twitter:card metatag is not a valid card type. Valid card types are 'app', 'player', 'summary' and 'summary_large_image'. (Card error)
```
Seems like that will solve the problem with generating previews in Twitter:
- changing `summary_image` to `summary`
=> Fix Twitter Card

frontend/static/css/components/posts.css
До:
После:
Если текст не влазит, то скроллбар появится.
=> Hide scrollbar if it's not needed in a `pre` block

frontend/html/comments/types/snippet.html, frontend/html/search.html, frontend/html/users/profile.html
Добавил новый шаблон для рендеринга комментов вне страницы комментариев.
Старался сделать как можно более легковесным. Выкинул все ссылки и vue-компонент голосования. Любой клик по блоку переносит на этот коммент в посте.
#332
=> Новый шаблон для рендеринга комментариев в поиске и профиле

frontend/static/js/App.js
Post editor should handle video files as a replacement
for gif files. And this feature established on the file server
and post templates, but code mirror file upload plugin
disallow upload videos by default. Fixed this.
Also, removed `convert_to` and `quality` extra params (they
handled by file server) because these parameters have no
sense if we upload files with different types.
NOTE: Video files upload works only via drag and drop,
not copy-paste.
https://github.com/vas3k/vas3k.club/issues/339
Wait for [this small issue](https://github.com/vas3k/vas3k.club/issues/339#issuecomment-669383319) in file server
=> WIP: Add video to allowed mime types for uploading #339

frontend/static/css/components.css
fix issue #169
Проблема была в том, что внутри компонента с редактором есть 2 элемента textarea: 
1. реальный textarea, который отображается на мобильных устройствах и скрывается после инициализации CodeMirror (для него эти стили полезны)
2. вспомогательный textarea внутри CodeMirror, и ему становится реально плохо от `min-height: 500px;`
теперь стили применяются только к настоящему textarea
=> Исправлено дерганье в сафари

frontend/static/css/components.css
В режиме отображения поста всё, что идёт в класс post-date отображается тупо с opacity: 0.6 при базовом цвете `#DDD`. Это соответствует значению `#858585`.
В режиме отображения закладок цвет количества комментариев установлен тупо на `#999`.
Соответственно получается небольшое отличие между ними.
Я слабо вижу эту разницу и предпочёл повторить поведение кнопки в режиме поста.
Если есть идеи лучше -  дай знать.
=> Improving CSS for bookmark controls

frontend/static/js/App.js, frontend/static/js/main.js
Сейчас в консоли на мобильной версии вываливается ошибка "Cannot read property 'forEach' of undefined".
Это связано со следующим куском кода:
````ts
const registeredEditors = this.initializeMarkdownEditor();
setTimeout(function () {
registeredEditors.forEach((editor) => {
// textarea value after navigation might be restored after codemirror inited
if (editor.element.value && !editor.codemirror.getValue()) {
editor.codemirror.setValue(editor.element.value);
}
});
}, INITIAL_SYNC_DELAY);
````
Для мобильной версии сайта вызов initializeMarkdownEditor возвращал undefined.
=> Fix console errors in mobile version

frontend/html/layout.html
Properly defines charset Error!
A character encoding declaration is required. It can be done with a <meta> tag in the first 1024 bytes of the HTML or in the Content-Type HTTP response header. Learn more.
https://web.dev/charset/?utm_source=lighthouse&utm_medium=devtools
=> Resolve charset declaration issue

frontend/static/js/inline-attachment.js
Фикс к этому:
https://github.com/vas3k/vas3k.club/issues/426
Почему фейлятся гифки, я не определила (я фронтендер 💁), но могу пофиксить отображение ошибки на фронте
=> Отображать ошибку, если падает запрос на загрузку media к комментарию

etc/nginx/i.vas3k.club.conf, etc/nginx/vas3k.club.conf
Я добавил то, что просто добавить. Есть пара нюансов:
- Про Permissions-Policy в комментариях говорят, что вроде ещё не все браузеры поддерживают по умолчанию (http://disq.us/p/2bxp2rt - комментарий от Craig Francis). Я все равно добавил, указал только, что мы можем геолокацию использовать (хз, используется уже или нет)
- Ещё возможно ты захочешь перепроверить Referrer-Policy - https://scotthelme.co.uk/a-new-security-header-referrer-policy/
- Не добавил Content-Security-Policy, там как-то не тривиально. Например, на том сайте такое значение:
> default-src 'self'; script-src 'self' 'report-sample' disqus.com c.disquscdn.com platform.instagram.com cdnjs.cloudflare.com scotthelme.disqus.com a.disquscdn.com go.disqus.com platform.twitter.com cdn.syndication.twimg.com syndication.twitter.com …
=> Adding easy security headers

frontend/static/css/components.css, frontend/static/css/layout.css
Closes #452
До:
```sh
webpack_1   |     WARNING in ./static/css/index.css (./node_modules/css-loader/dist/cjs.js??ref--0-1!./node_modules/postcss-loader/src!./static/css/index.css)
webpack_1   |     Module Warning (from ./node_modules/postcss-loader/src/index.js):
webpack_1   |     Warning
webpack_1   |     
webpack_1   |     (777:9) start value has mixed support, consider using flex-start instead
```
После: 
No more WARNING 👌
=> Get rid of postcss warning

frontend/package-lock.json
```sh
webpack_1   | Browserslist: caniuse-lite is outdated. Please run:
webpack_1   | npx browserslist@latest --update-db
```
Updated to the latest version by running the command suggested above.
=> Browserslist: caniuse-lite is outdated

frontend/html/common/menu-full.html, frontend/html/common/menu-simplified.html, frontend/html/landing.html, frontend/html/layout.html, frontend/html/sidebar_layout.html
The page does not contain a heading, skip link, or landmark region 
- https://web.dev/bypass/?utm_source=lighthouse&utm_medium=devtools
As a bonus, it also brings semantically correct HTML elements.
=> Improve keyboard navigation [Lighthouse]

frontend/html/users/edit/notifications.html, frontend/html/users/intro.html, frontend/static/css/components.css
Сейчас радиокнопки торчат прямо посередине блока-выбиралки и загораживают собой текст.
Если спрятать их через visibility: hidden — они по прежнему будут кликабельными, а текст будет красивым.
Вот так выглядит сейчас:
=> Hide native radio button on user digest selector

frontend/static/css/fonts.css
The `local()` function allows users to use their local copy of the font if present instead of downloading it.
Before:
After:
=> Prevent webfonts double-loading

frontend/static/css/components/people.css
Добавил тень для текста по мотивам ишака #478 
Теперь на светлом фоне каунтер читается без проблем
=> Added text-shadow for counter in people map

frontend/static/js/App.js
В соответсвии с https://github.com/Ionaru/easy-markdown-editor/pull/143 и как описано в документации
Closes #486
=> Turning on a native browser spell-checker

frontend/static/css/components.css
Измененный вариант справа. 
Делает более заметными новые комменты в длинной простыне.
=> Фича: Более светлый фон для новых коментариев в темной теме.

frontend/static/css/components/posts.css
Removes scroll, when it's not needed.
=> Fix unwanted scroll on linked post block

common/markdown/plain_renderer.py
Сейчас все уведомления в телеге затирают ссылку если в маркдауне ссылка была спрятана за текстом, приходилось открывать комментарий чтобы посмотреть на ссылку, это неудобно.
В идеале было бы сделать с помощью нативной ссылки в телеграме, но там дальше по коду все html теги обрезаются, не хотел сильно ломать эту логику.
=> Added link to telegram renderer

posts/templatetags/query_params.py
Пример:
на странице https://vas3k.club/people/?query=&country=&tags=work-hard&tags=extrovert ссылка на следующую страницу содержит только один тэг
`<a href="?query=&amp;country=&amp;tags=extrovert&amp;page=2" class="paginator-page ">2</a>`
=>  fix /people/ page pagination with multiple tags: removed the disappearance of parameters

frontend/html/common/menu-full.html, frontend/static/css/components.css
#413 annoys me greatly so I decided to look at least for a quick fix that I can implement and make my mobile experience better.
The bug has been introduced in #372. PR author intention was hiding "Пиши" button caption on narrow screens but accidentally he used the same class name that is being used on a [div wrapper](https://github.com/vas3k/vas3k.club/blob/master/frontend/html/posts/compose/intro.html#L11) in [all](https://github.com/vas3k/vas3k.club/blob/master/frontend/html/posts/compose/link.html#L30) [post create/edit templates](https://github.com/vas3k/vas3k.club/blob/master/frontend/html/posts/compose/idea.html#L29).
Class name update seems to solve the issue
**UPD**
"Пиши" caption remains hidden on mobiles
=> Fix #413: prevent intro edit from hiding on mobiles

common/markdown/club_renderer.py, frontend/html/posts/embeds/youtube.html
Сначала хотел добавить только `allowfullscreen` (ибо бесит, что нельзя видосы открыть на фуллскрин), а потом решил докинуть и остальное, что предлагает стандартно сам ютуб, когда хочешь встроить видео с него куда-то.
=> Добавил allow-атрибуты в ютубовский встраиваемый плеер

notifications/telegram/users.py
Небольшой фикс уведомлений в админ-чат о письме пользователю от модератора и о размодерировании.
Суть фикса в том, что уведомления направляются в `ADMIN_CHAT`, но стояли за if'ом на наличие привязанного бота у юзера, который я и убрал (из-за if'а не все уведомления попадали в админ-чат).
=> fix some telegram admins notifications

frontend/static/js/components/UserExpertiseWindow.vue
The issue is caused by `expertise_custom` being submitted even when it's not visible because of using the `v-show` directive instead of the conditional rendering one (`v-if`).
=> Fix #632: custom expertise is submitted even if not selected

frontend/static/css/layout.css, frontend/static/js/App.js
На macOS - shift-ctrl-up/down. Потому что Mission Control.
Кажется, получилось попроще, чем на той же Лепре. Без внешних библиотек и Javascript посовременнее.
При скачке элемент фокуса моргает прозрачностью треть секунды.
Safari скачет без анимаций, т.к. не умеет в `behavior: "smooth"`.
Можно исправить полифилом https://github.com/iamdustan/smoothscroll
Но кажется, полифил будет лишним.
https://user-images.githubusercontent.com/3754755/129095582-9d1902cb-904f-41cb-bd84-30aa327dc498.mp4
=> Скроллинг комментариев кнопками ctrl-up/down #662

common/url_metadata_parser.py, frontend/html/posts/embeds/summary.html, posts/templatetags/posts.py
Проблема вызвана кривым кодом в библиотек newspaper3k, который не очень корректно обрабатывает title из одних только русских символов (точнее комбинация двух ошибок, в extractors.py:289 и extractors.py:347).
Можно было бы починить библиотеку, но она не выглядит активной.
Предлагается сразу два фикса:
1) сохранять дополнительно meta_description из newspaper.Article. Если title пустой, а description нет - использовать его.
2) если оба пустые, показывать просто урл.
Для конкретный ссылки из бага, будет выглядеть так:
Существующие ссылки естественно автоматом не будут обновлены, репортер бага должен будет пересохранить пост.
=> Fixing issue #667

frontend/static/css/components.css
paginator-page has incorrect background for long page numbers (i.e. 100) due to the fixed width.
Env: Latest Safari and Firefox on macOS 11.x
=> Fix paginator-page background for long page numbers

common/markdown/club_renderer.py, frontend/html/layout.html, frontend/html/posts/show/layout.html, frontend/static/css/components.css, frontend/static/css/components/comments.css, frontend/static/css/layout.css, frontend/static/js/App.js, frontend/static/js/common/utils.js, frontend/static/js/components/CommentScrollArrow.vue, frontend/static/js/components/InputLengthCounter.vue, frontend/static/js/main.js
**Issue:** https://github.com/vas3k/vas3k.club/issues/491
**ПР использует механику уже существующего скроллинга комментариев кнопками ctrl-up/down, которую реализовал @simnv :** https://github.com/vas3k/vas3k.club/pull/663
**Что я добавил/изменил:**
- Добавил кнопку со стрелкой на страницах, где есть комментарии (логика реализации: https://github.com/vas3k/vas3k.club/issues/491#issuecomment-932042851)
- Перенёс логику скролла  кнопками ctrl-up/down (initializeCommentScroll) в компонент (практически as is, без изменений)
- Поменял доскролл к низу страницы на доскролл к полю комментирования
- Починил анимацию подсвечивания коммента, к которому подскролл (оставил как было blink анимацию, пишите если есть предложения как улучшить)
- Вынес функцию throttle в utils, т.к. она стала …
=> [feature] Скроллинг по непрочитанным комментариям + кнопка «наверх»

frontend/static/css/components/stats.css
Небольшой фикс: исправление центрирования ачивок на мобильных
К #694 
<details>
<summary>Изменение</summary>
| ![Before](https://user-images.githubusercontent.com/43755002/144449454-43ec50b1-cc0f-4d9d-977e-70906efc5777.png) | ![After](https://user-images.githubusercontent.com/43755002/144449980-e0f97c02-61de-46b4-b945-3fb69a188045.png) |
|:---:|:---:|
| До | После |
</details>
=> Fix achievements centering on mobile

users/views/muted.py
Хотфикс возможности самомьюта.
_Небольшое замечание_: если пользователь на проде замьютил себя ДО и так оставил, после слияния с мастер-веткой и сборкой в проде, размьютить он себя без помощи админа не сможет, т.к. логика хотфикса выбрасывает исключение без проверки на замьюченность.
Closes #856
=> fix: Самомьют!

frontend/html/users/admin.html, misc/views.py, users/admin.py, users/forms/admin.py, users/models/user.py, users/utils.py
Как и обсуждалось в [issue](https://github.com/vas3k/vas3k.club/issues/872) добавил больше полей в админскую панель.
Выглядит это так:
Так же сделал небольшие дополнительные изменения по правилу бойскаута (комментарии оставлены ниже).
=> Add more User fields to admin panel #872

notifications/telegram/users.py
Сделано по https://github.com/vas3k/vas3k.club/discussions/850. 
Одноразовый код для входа в клуб можно нажать, чтобы скопировать в буфер обмена, но это не работало в телеграм клиенте на macOS. Теперь должно работать везде.
=> Clickable telegram code on macOS

Dockerfile
Фикс: https://github.com/vas3k/vas3k.club/issues/757
Добавил две зависимости при сборке докер образа: `build-essential` и `python3-dev`. Работает только если обе добавить.
После этого проект собрался и запустился без проблем через `docker-compose up`
=> Пофиксил запуск проекта для MacOS на M1

frontend/html/users/profile.html
Because // floor division is used for both months and years let's show 23-something-months old accounts as 23 months old, not as a year old.
=> Fix 24 months old profiles being shown as year old

frontend/static/css/base.css
Поправил radio элементы на маленьких разрешениях, [багрепорт](https://github.com/vas3k/vas3k.club/issues/936).
На скриншотах слева до, справа после.
=> Fix radio items on small resolutions

.github/workflows/codeql-vulnerability-analysis.yml
> On March 30, 2022, we released CodeQL Action v2, which runs on the
> Node.js 16 runtime. The CodeQL Action v1 will be deprecated at the same
> time as GHES 3.3, which is currently scheduled for December 2022.
https://github.blog/changelog/2022-04-27-code-scanning-deprecation-of-codeql-action-v1/
=> Upgrade CodeQL Action to v2

bot/main.py
Я часто тихонько пересылаю чье-то чужое сообщения из "Бара" в бота и делаю "/whois". Это происходит четыремя сообщениями:
Если этот PR будет принят, whois будет сразу срабатывать на все forwards в приватных сообщениях. То есть после форварда "Вастрика" сразу придет "Кажется, он скрыл профиль..."
А еще мозолящую глаз опечатку убрал. На скрине она тоже видна.
=> Автоматический /whois на все форварды в личке бота

bot/handlers/whois.py, bot/main.py
Так, прошу прощения за недоделанный #979, почему-то думал, что жизнь простая, shit happens. В прошлом PR форварды обрабатывались как обычный whois и падали на первой же проверке, потому что не было реплая.
В этот раз whois действительно срабатывает, как ожидается:
1. (без изменений) реплаем с командой /whois в личке и в группе на обычное сообщение
2. (без изменений) реплаем с командой /whois в личке и в группе на форвард
3. обычным форвардом в личку (ожидаемо не стриггерится на форвард в группе)
=> fix: auto-whois in command_whois

frontend/static/js/components/CommentScrollArrow.vue
Assigning the value behaves as a `location.push` and adds a new item into the `history` which makes it hard for users to jump to the previous **page** i.e. feed.
Replacing, on the other hand, allows going to the previous page with a single "go back".
See also: https://github.com/vas3k/vas3k.club/discussions/1001
=> Replace history in 'CommentScrollArrow'

.github/workflows/tests.yml
* Get rid of `docker-compose` execution for tests. Use `postgres` and `redis` services instead
* Use python 3.8 and node 14 to replicate `docker-compose` setup
* Use cache for pip packages and webpack build.
* postgres 12 as in prod docker-compose
Fixes #996
=> Speed up tests in CI

posts/templatetags/text_filters.py
Новая попытка пофиксить критикал баг #798. Даже сейчас у [вастрика](https://vas3k.club/user/vas3k/) отображается только 3к плюсиков, когда должно быть, скорее всего, 33к
=> Wrong profile pluses counter for 1k+ trailing zeroes values

frontend/html/comments/types/reply.html
По аналогии как недавно было выяснено, что в реплаях не хватает проверок на `is_commentable`, добавил туда проверку на активную подписку
Было:
Стало:
=> Add user active membership check in replies

search/models.py, search/tests.py, users/views/people.py
Исправляет проблему из #713.
Пришлось кроме вектора с конфигом "russian", добавить еще вектор "simple". Это позволяет искать точные формы слов и ранжировать их выше чем базовые. Это решает проблему с поиском по слову домен и т.п.. Но скорее всего таблица с `SearchIndex` увеличится раза в два.
Заодно перевел поисковый синтакс на режим "websearch" - он позволяет писать поисковые запросы примерно как в google. Например `"sad cat" or "fat rat"`. Это должно быть бесплатно (пока нет возможности проверить на большом объеме).
Добавил базовые тесты на search.
=> Fix: #713 - Возможность искать точные формы слов без стемминга

users/views/people.py
If the database were empty, previous code would raise KeyValue.
Closes: #1055
=> fix: KeyValue on /people/

frontend/html/auth/access_denied.html, frontend/html/emails/weekly.html, frontend/html/emails/weekly_og_description.html, notifications/digests.py, notifications/management/commands/send_weekly_digest.py, notifications/views.py
og:description is not visible at access_denied page (which page is seen by telegram or twitter or face book)
So in this commit description is writting to post.metadata and rendering at access_denied.html
=> Add og:description to private weekly_digest page

frontend/static/css/components/menu.css
=> fix missing search icon on small screens

frontend/html/posts/show/battle.html, frontend/static/js/components/CommentScrollArrow.vue
#1070  In battles second level comments in fact are third levels, and go to new message skips them.
=> fix(): enable go to second level comments in battles

notifications/management/commands/send_weekly_digest.py
Сейчас ссылка в письме на отписку генерируется в коде только один раз. И во всех письмах она работает на отписку одного и того же пользователя (вот же бедолага!)
=> Make unsubscribe button in weekly_digest email work properly

frontend/static/css/layout.css
В темной теме скроллбар выглядел ужасно, добавил кастомизацию с цветами темы
Было:
Стало:
В светлой теме
Было:
Стало:
=> Добавил кастомизацию цвета скроллбара

frontend/static/css/components/network.css
before:
after:
Текущая реализация корректно работает для беджей с одним эмодзи, но плывет при 2+.
=> fix: border-radius for .network-channel-badge

frontend/html/comments/types/reply.html
- пофексил баг, при котором кнопка "редактирования" для реплаев показывалась автором поста
- изменил рестрикшенсы для реплаев по аналогии с комментариями
До:
После:
=> Hide reply edit button for post's authors

comments/tests/test_comments.py, comments/views.py
**Проблема:** не приходят уведомления с новыми комментами 2 уровня и ниже для авторов поста 
**Что сделал:** 
**1)** Добавил простую проверку на подписку, чтобы отправление нового коммента не понижало статус авторской подписки на комменты. 
То есть чтоб новые комменты от автора с помеченной галкой на подписку (внизу) не сбрасывали с
PostSubscription.type = Type.ALL_COMMENTS
до 
PostSubscription.type = Type.TOP_LEVEL_ONLY.
src="https://github.com/vas3k/vas3k.club/assets/91570054/253a1110-3bcb-440f-a868-7217b122ef72">
**2)** Написал пару тестов для этого.
**Проблема/Для обсуждения:** В текущей реализации у автора сохраняется подписка на все комменты всех уровней, пока он не отожмет _**верхнюю**_ галку подписи на комменты. Если он отожмет — возможности подписаться на все комменты в этом …
=> fix: rework notify-subscription for authors (notifies for second layer and etc)

frontend/static/js/components/TagSelect.vue
Add filter function to hide «standard» tags
Diff prod vs fix:
=> bugfix: TagSelect show only collectible tags

frontend/static/css/layout.css
I am adding screenshots before and after adjusting comment form width to 100% to prevent overflow:
=> bugfix: adjust comment form width to 100% to prevent overflow

authn/management/commands/import_posts_to_dev.py, docs/setup.md
Хочу [подбить поиск](https://github.com/vas3k/vas3k.club/issues/1052#issuecomment-2168355418), мантикора смотрится вполне интересным вариантом. Для тестов столкнулся с тем. что не плохо бы иметь на локалке "живые" посты. 
Накидал команду, которая парсит https://vas3k.club/feed.json, собирает там публичные посты (чтобы был полный текст, а не обрывки) и вставляет всё это добро в локальную базу. 
```bash
$ python3 manage.py import_posts_to_dev [--pages PAGES] [--skip SKIP] [--force] 
Импорт постов с оригинального vas3k.club на dev/local сборки
optional arguments:
--pages PAGES         Количество страниц, забираемых и фида
--skip SKIP           Количество страниц, которые надо пропустить
--force               Заменять посты, если они уже существуют
```
```bash
$ python3 manage.py …
```
=> Импорт публичных постов из основного клуба в dev/local среду

frontend/html/comments/types/reply.html, frontend/static/js/components/ReplyContainer.vue, frontend/static/js/main.js
Исправляет баг, когда форма отправки комментария показывает имя другого пользователя.
Новой форма отправки ответов на комментарии (#1216) сохраняет написанный, но неотправленный комментарий. Для сохранения она использует айдишник комментария, на который отправляется ответ. 
Проблема была в том, что на последнем уровне глубины мы отправляем ответ не на текущий комментарий, а на родительский:
Возникает коллизия ключей и сохраненный ответ к другому комментария достается из памяти.
Добавил опциональный ключ, который отправляется при ответе на комментарии последнего уровня.
=> Фиксит сохранение неотправленных ответов

frontend/static/js/components/MarkdownEditor/DesktopMarkdownEditor.vue, frontend/static/js/components/MarkdownEditor/MarkdownEditor.vue, frontend/static/js/components/MarkdownEditor/MobileMarkdownEditor.vue, frontend/static/js/components/ReplyForm.vue, frontend/static/js/main.js
Выделяет логику работы мобильного и десктопного редакторов в отдельные компоненты.
Мы хотим добавить загрузку картинок. Со старым подходом к логике становится сложно держать в голове задачу. Всё поведение хранится в одном компоненте и переключается с помощью `if (isMobile) {...}`, плюс `ReplyForm` лезет внутрь редактора и добавляет свою логику поверх.
`ReplyForm` использует фасад в виде `MarkdownEditor`, который в свою очередь решает, что ему рендерить `MobileMarkdownEditor` (простая textarea) или `DesktopMobileEditor` (полноценный маркдаун)
=> Разделяет код мобильного и десктопного редакторов

frontend/static/css/components/comments.css, frontend/static/js/components/ReplyForm.vue
Делает две вещи:
- увеличивает шрифт до 16 пикселей в полях ответов на мобиле. Это позволяет избежать [призумливания на мобильных сафари](https://css-tricks.com/16px-or-larger-text-prevents-ios-form-zoom/)
- Откладывает прокрутку до поля ответа на 50мс. Это позволяет дождаться появления виртуальной клавиатуры и прокручивать уже имея ее на экране. Без задержки [клавиатура на iOS сдвигает сайт вверх](https://stackoverflow.com/questions/56351216/ios-safari-unwanted-scroll-when-keyboard-is-opened-and-body-scroll-is-disabled)
=> Правит прокрутку до поля ответов в iOS

frontend/static/js/components/ReplyForm.vue
Обратил внимание, что мы прокручиваем к последней форме ответа в момент, когда форма теряет фокус:
[](https://github.com/user-attachments/assets/f9ba58d0-97ab-421a-88f0-3df3a32a2431)
Проверяет, что флаг `isFocused` взведен прежде чем запланировать прокрутку:
[](https://github.com/user-attachments/assets/f727102f-7c91-437b-aba5-04acac2f9730)
=> Убирает прокрутку к последнему полю ответа при уходе фокуса

frontend/static/js/components/MarkdownEditor/MobileMarkdownEditor.vue, frontend/static/js/inline-attachment.js
Обратил внимание, что все прошлые варианты загрузки возвращают фокус в поле ввода. Добавил, чтобы и после загрузки через кнопку фокус возвращался в поле. Для десктопа он возвращается в какое-то странное место, но это поведение аналогично тому, что есть и при драг-н-дропе 
[](https://github.com/user-attachments/assets/adb6a0aa-0c93-4f00-8930-402ffc1ee9bc)
=> Перемещает фокус в редактор текста после загрузки картинки

authn/models/openid.py, authn/providers/openid.py
Issue: https://github.com/vas3k/vas3k.club/issues/1252
Выставил 
[OpenIDCode(require_nonce=False)]
и пара проверок на None
Но я не настоящий сварщик поэтому прошу ревью)
=> OpenID - non require nonce parameter

frontend/static/js/common/markdown-editor.js
Включил возможность добавлять webp-изображения на фронте, [по запросу](https://vas3k.club/post/26312/#comment-1877bfa7-331c-4029-9d49-03dd809f633d) из поста про [Хактоберфест](https://vas3k.club/post/26312/)
На бэке уже работает (конвертирует в jpg), оставалось разрешить на фронте
=> feat: allow uploading webp images

frontend/html/comments/types/battle.html, frontend/static/css/components/comments.css, frontend/static/css/components/posts.css, frontend/static/css/layout.css, frontend/static/js/components/CommentScrollArrow.vue
По просьбам трудящихся
https://vas3k.club/post/26312/#comment-0fc85b28-b8b8-456e-aeb2-694f0572cb4b
Основная проблема в том, что по логике `CommentScrollArrow.vue` мы листаем комменты/реплаи, у которых есть атрибут `id^=comment-`. В батлах же атрибут `id="comment-bla-bla-bla"` у родительского элемента. Судя по всему, это сделано из-за наличия доп. элементов внутри "основного коммента". Однако `CommentScrollArrow.vue` так не работает и всё ломается. 
Перенёс идентификатор к элементу `class=comment`, а так же пришлось немного поверстать. 
Подробнее по коду в ревью пробегусь. 
В ЛИСЕ ПРОВЕРИЛ!!!
=> Листаем комменты в батлах с помощью кнопки `comment-scroll-arrow`

frontend/html/comments/types/bold.html, frontend/static/js/components/CommentScrollArrow.vue
Опять просьбы трудящихся (когда же они уже успокоятся?)
https://vas3k.club/post/26312/#comment-5532fd68-5cd6-4583-8017-e741315aa244
Проблема аналогичная как с батлами, элемент с `class=comment` не получал атрибута id и это ломало метод листания комментов. Решил по аналогии с батлами + добавил в `querySelector` с поиском новых комментов в том числе ответы на запиненные комменты. По аналогии с батлами, изменения затронули исключительно запиненные комменты, всё должно быть ровно. 
p.s. так же вастрикан просил поменять фон закреплённого коммента в светлой теме, типа его не видно, но это уже не ко мне. чукча не дизайнер, чукча баголеп. 
В ЛИСЕ ПРОВЕРИЛ!!!
=> Закреплённые комменты ломали `CommentScrollArrow`

frontend/static/js/components/CommentScrollArrow.vue
Поменял тег для кнопки `comment-scroll-arrow` со `span` на `button`.
Это нужно для:
- семантики
- возможности сфокусироваться на кнопке через tab
- корректной работы расширения [Vimium](https://chromewebstore.google.com/detail/vimium/dbepggeogbaibhgnhhndojpepiihcmeb?hl=en)
[Запрос на фикс](https://vas3k.club/post/26312/#comment-f8843113-260a-4a9d-a985-30468f0f8518) в треде "Объявляется внеочередной сбор идей и фич для Клуба"
=> Use <button> tag for the <comment-scroll-arrow> component

users/models/friends.py, users/views/friends.py
В api_friend добавлена проверка, запрещающая пользователям отправлять запросы на добавление в друзья самим себе.  
Ранее конечная точка разрешала такие запросы, что приводило к недействительным записям в таблице друзей.  
Теперь, если `user_from == user_to`, будет поднят соответствующий ApiException с ответом 400.
Fixes: https://github.com/vas3k/vas3k.club/issues/1306
=> fix(api): prevent users from adding themselves as friends

common/data/achievements.py
Папарации было неправильным словом
Надеюсь, выдача ачивок привязана к id, а не к имени ачивки. Но если что, у меня есть список ее получавших
=> FIx astrophoto achievement name

users/views/muted.py
- Fix issue where users at max mute limit couldn't unmute anyone
- Move mute limit validation to only apply when creating new mutes
When a user reached the maximum mute limit (20 users), they were unable to unmute anyone because the validation check happened before determining whether the action was a mute or unmute operation.
- Check if target user is already muted before applying limit validation
- Only prevent new mutes when at the limit, allow unmuting existing mutes
- Change comparison from `>` to `>=` for more accurate limit checking
=> Fix unmute functionality when max mute limit reached

frontend/static/css/components/posts.css
Что сделал: чуть подвинул кнопку для голосования за статью. Она часто налазит на изображения в статье.
До:
После:
=> fixed upvote button overlap with post images

common/regexp.py, godmode/pages/mass_achievement.py
Изменения:
1. Теперь разных пользователей надо вводить через перенос строки или пробел,
2. Можно вводить слаги как раньше, а можно вводить ссылку на профиль.
Это потому что мне проще всего выдавать массовые ачивки, копируя ссылку с профиля или из результата команды /whois:
Локально проверил.
=> feat: give mass achievements by urls
